export const types = {
    GET_DATA_SUCCESS: '[auth] GET_DATA_SUCCESS',
    GET_DATA_FAILURE: '[auth] GET_DATA_FAILURE',
    GET_DOCUMENTS: '[documents] GET_DOCUMENTS',
    GET_DOCUMENT_SUCCESS: '[documents] GET_DOCUMENT_SUCCESS',
    GET_SELECTED_USER: 'GET_SELECTED_USER',
    UPDATE_DOCUMENT_SUCCESS: '[documents] UPDATE_DOCUMENT_SUCCESS',
}